# Generated by Django 4.2.5 on 2023-09-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('BMW', 'Bmw'), ('Other', 'Other')], default='Other', max_length=20)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
    ]
